title: Tasks
href: index.md
items: 
  - name: Overview of Methods
    href: index.md
  - name: New Task Card
    href: tasks-new.md    
  - name: Task Fields
    href: fields.md
  - name: Add Task
    href: tasks-task-add.md
  - name: Update Task
    href: tasks-task-update.md
  - name: Get Task by ID
    href: tasks-task-get.md
  - name: Get Task List
    href: tasks-task-list.md
  - name: Delete Task
    href: tasks-task-delete.md
  - name: Get Field List
    href: tasks-task-get-fields.md
  - name: Check Access to Task
    href: tasks-task-get-access.md
  - name: Attach Files to Task
    href: tasks-task-files-attach.md
  - name: Get User Counters
    href: tasks-task-counters-get.md
  - name: Delegate Task
    href: tasks-task-delegate.md
  - name: Accept Task
    href: tasks-task-approve.md
  - name: Reject Task
    href: tasks-task-disapprove.md
  - name: Add Task to Favorites
    href: tasks-task-favorite-add.md
  - name: Remove Task from Favorites
    href: tasks-task-favorite-remove.md
  - name: Task History
    href: tasks-task-history-list.md
  - name: Start Watching Task
    href: tasks-task-start-watch.md
  - name: Stop Watching Task
    href: tasks-task-stop-watch.md
  - name: Move Task to In Progress Status
    href: tasks-task-start.md
  - name: Move Task to Waiting for Execution Status
    href: tasks-task-pause.md
  - name: Move Task to Deferred Status
    href: tasks-task-defer.md
  - name: Move Task to Completed Status
    href: tasks-task-complete.md
  - name: Renew Task After Completion
    href: tasks-task-renew.md
  - name: Enable Silent Mode
    href: tasks-task-mute.md
  - name: Disable Silent Mode
    href: tasks-task-unmute.md
  - name: Create Dependency Between Tasks
    href: task-dependence-add.md
  - name: Remove Dependency Between Tasks
    href: task-dependence-delete.md
  - name: Task Result
    include:
      path: result/b24-toc.yaml
      mode: link
  - name: Events
    include:
      path: events-tasks/b24-toc.yaml
      mode: link
  - name: Checklists
    include:
      path: checklist-item/b24-toc.yaml
      mode: link
  - name: Comments
    include:
      path: comment-item/b24-toc.yaml
      mode: link
  - name: Time Spent
    include:
      path: elapsed-item/b24-toc.yaml
      mode: link
  - name: Custom Fields
    include:
      path: user-field/b24-toc.yaml
      mode: link
  - name: Kanban and My Plan Stages
    include:
      path: stages/b24-toc.yaml
      mode: link
  - name: Tasks in Daily Plan
    include:
      path: planner/b24-toc.yaml
      mode: link
  - name: Flows
    include:
      path: flow/b24-toc.yaml
      mode: link
  - name: Deprecated
    include:
      path: deprecated/b24-toc.yaml
      mode: link