title: Checklists
href: index.md
items:
  - name: Overview of Methods
    href: index.md
  - name: Add Checklist Item
    href: task-checklist-item-add.md
  - name: Update Checklist Item
    href: task-checklist-item-update.md
  - name: Get Checklist Item by ID
    href: task-checklist-item-get.md
  - name: Get List of Checklist Items
    href: task-checklist-item-get-list.md
  - name: Delete Checklist Item
    href: task-checklist-item-delete.md
  - name: Move Checklist Item
    href: task-checklist-item-move-after-item.md  
  - name: Mark Item as Completed
    href: task-checklist-item-complete.md
  - name: Mark Item as Incomplete
    href: task-checklist-item-renew.md
  - name: Check Action Permission
    href: task-checklist-item-is-action-allowed.md
  - name: Get List of Methods and Their Descriptions
    href: task-checklist-item-get-manifest.md